In [2]:
import torch
import torch.nn as nn
import numpy as np

In [3]:
a = np.random.randn(2,3)
a

array([[ 0.06241345,  1.07564849, -0.9349628 ],
       [-0.30374308, -0.91177374, -0.90507812]])

In [ ]:
t = torch.Tensor(a)
t

tensor([[ 0.0624,  1.0756, -0.9350],
        [-0.3037, -0.9118, -0.9051]])

In [5]:
t2 = torch.tensor(a)
t2

tensor([[ 0.0624,  1.0756, -0.9350],
        [-0.3037, -0.9118, -0.9051]], dtype=torch.float64)

In [10]:
t.type(), t2.type()

('torch.FloatTensor', 'torch.DoubleTensor')

In [12]:
t3 = torch.tensor(a, dtype=torch.int64)
t3

tensor([[0, 1, 0],
        [0, 0, 0]])